# tests/testthat/test-plot_generation.R
library(testthat)
# No specific libraries like dplyr/readxl needed here if we source the main script,
# as it should load its own dependencies.
# However, ggplot2 and scales are used for plotting in the main script.

context("Plot Generation (File Existence)")

# List of expected plot files
plot_files <- c(
  "graficoGestantesCor.png",
  "graficoGestantesCorFreq.png",
  "graficoGestantesEstadoCivil.png",
  "graficoGestantesEstadoCivilFreq.png"
)

# Test setup: Remove existing plot files before running the script
# This ensures that the test checks for files created by *this* run.
setup({
  # message("Removing existing plot files (if any)...")
  for (file_path in plot_files) {
    if (file.exists(file.path("../../", file_path))) { # Check from tests/testthat to project root
      file.remove(file.path("../../", file_path))
    }
  }
})

# Source the main script to generate plots.
# This is a broad approach. If the script is very long or has issues
# with being sourced multiple times, more targeted sourcing or refactoring
# of the main script into functions would be better.
# For now, we assume the main script can be sourced.
# Suppress messages and output from source() unless it's an error.
# The `tryCatch` is to ensure tests can still complete if the main script has an error.
script_sourced_successfully <- FALSE
source_output <- NULL
main_script_path <- "../../2025_03_29_analisesGestantes.R" # Relative to tests/testthat/

if (!file.exists(main_script_path)) {
  warning(paste("Main script not found at:", main_script_path, " - Plot generation tests will be skipped."))
} else {
  tryCatch({
    # message(paste("Sourcing main script:", main_script_path))
    # Use chdir = TRUE to run the script from its own directory if it uses relative paths internally for data.
    # However, our data loading is explicit from project root.
    # We need to ensure the sourced script can find its data file.
    # The data file path in main script is "BD_completo_corrigido_12-02-2025.xlsx"
    # So, the sourced script should be run from the project root.
    # testthat runs tests with the working directory set to tests/testthat.
    # We need to temporarily change to project root for sourcing the script.
    
    # Get current working directory
    original_wd <- getwd()
    # Change to project root (assuming tests/testthat structure)
    setwd("../..") 
    
    # Source the script
    # Capture output to avoid cluttering test results, show only if error
    source_output <- capture.output(source(basename(main_script_path), echo = FALSE, print.eval = FALSE), type="message")
    
    # Change back to original working directory
    setwd(original_wd)
    
    script_sourced_successfully <- TRUE
    # message("Main script sourced successfully for plot tests.")
  }, error = function(e) {
    message("Error sourcing main_script.R for plot generation tests:")
    message(conditionMessage(e))
    if (!is.null(source_output)) print(source_output) # Print any captured output if error
    script_sourced_successfully <- FALSE
  })
}


test_that("Main script runs without error for plot generation", {
  if (!file.exists(main_script_path)) {
      skip(paste("Main script not found at:", main_script_path))
  }
  expect_true(script_sourced_successfully, "Main script should source without throwing an error for plot tests.")
})

test_that("All expected plot PNG files are generated", {
  if (!script_sourced_successfully) {
    skip("Skipping PNG file check as main script failed to source.")
  }
  
  # The `plot_files` variable contains paths relative to project root.
  # When test_that runs, wd is tests/testthat.
  # So we need to check `../../file_name.png`
  
  for (file_path in plot_files) {
    check_path <- file.path("../../", file_path) # Correct path from tests/testthat to project root file
    msg <- paste("Plot file", file_path, "should be generated by the script and exist at project root.")
    expect_true(file.exists(check_path), info = msg)
  }
})

# Teardown: Optionally remove the generated files after tests
# teardown({
#   message("Cleaning up generated plot files...")
#   for (file_path in plot_files) {
#     check_path <- file.path("../../", file_path)
#     if (file.exists(check_path)) {
#       file.remove(check_path)
#     }
#   }
# })
